services:
  redis:
    image: redis:7-alpine
    container_name: hotel-redis
    restart: unless-stopped

    ports:
      - "6380:6379"

  postgres:
    image: postgres:16-alpine
    container_name: hotel-postgres
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - hotel_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    container_name: hotel-backend
    restart: unless-stopped

    depends_on:
      - postgres
      - redis

    env_file:
      - .env

    ports:
      - "8000:8000"

  platform:
    build:
      context: .
      dockerfile: Dockerfile.platform

    container_name: hotel-platform
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - backend

    ports:
      - "3000:3000"

  tenant:
    build:
      context: .
      dockerfile: Dockerfile.tenant

    container_name: hotel-tenant
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - backend

    ports:
      - "3001:3000"

volumes:
  postgres_data: