FROM node:20-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/tenant/package.json ./apps/tenant/package.json
COPY packages ./packages

RUN npm ci


FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run build -w tenant


FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/tenant/public ./apps/tenant/public

COPY --from=builder --chown=nextjs:nodejs \
  /app/apps/tenant/.next/standalone ./

COPY --from=builder --chown=nextjs:nodejs \
  /app/apps/tenant/.next/static \
  ./apps/tenant/.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "apps/tenant/server.js"]