FROM node:20-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/platform/package.json ./apps/platform/package.json
COPY packages ./packages

RUN npm ci


FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build -w platform


FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/platform/public ./apps/platform/public

COPY --from=builder --chown=nextjs:nodejs \
  /app/apps/platform/.next/standalone ./

COPY --from=builder --chown=nextjs:nodejs \
  /app/apps/platform/.next/static \
  ./apps/platform/.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "apps/platform/server.js"]